<x-layouts.app title="แก้ไขเอกสาร">
    @include('site.admin._nav')

    <x-page-header title="แก้ไขเอกสาร" :subtitle="$document->title">
        @if ($document->is_published && $document->published_at && $document->published_at->isPast())
            <x-btn :href="route('site.document', $document)" target="_blank" variant="secondary" icon="external-link">
                ดูหน้านี้
            </x-btn>
        @endif
    </x-page-header>

    <div class="grid gap-6 lg:grid-cols-[1fr_260px]">
        <div class="card card-pad">
            <form method="POST" action="{{ route('site.documents.update', $document) }}" enctype="multipart/form-data" class="space-y-5">
                @csrf
                @method('PUT')

                @include('site.admin.documents._form')

                <x-form.actions :cancel="route('site.documents.index')" />
            </form>
        </div>

        <div class="card card-pad h-fit text-center">
            <h2 class="section-title mb-3">QR Code</h2>

            {{--
                Unescaped deliberately: the SVG is generated by BaconQrCode from
                a URL this application built, not from anything a user typed.
            --}}
            <div class="mx-auto w-[200px]">{!! $qrCode !!}</div>

            <p class="mt-3 text-xs text-slate-500">
                สแกนแล้วเปิดหน้าเอกสารนี้ พิมพ์ติดบอร์ดหรือแนบไปกับหนังสือได้
            </p>

            <p class="mt-2 break-all text-xs text-slate-400">{{ route('site.document', $document) }}</p>
        </div>
    </div>
</x-layouts.app>
