#!/usr/bin/env bash
#
# Reports this machine's inventory to the hospital back-office.
#
# Collects hardware, OS, and installed-package details and posts them to
# /api/agent/computer-inventory, authenticating with the bearer token from
# config.json.
#
# Needs only bash, curl, and the coreutils present on a default server install.
# jq is used when available and worked around when it is not, so nothing has to
# be installed on the fleet.
#
# Usage:
#   ./report-inventory.sh              send a report
#   ./report-inventory.sh --dry-run    print the payload without sending
#   ./report-inventory.sh --config /path/to/config.json
#
# Run daily from cron, jittered so a fleet does not arrive at once:
#   17 8 * * *  root  sleep $((RANDOM \% 1800)); /opt/hospital-agent/report-inventory.sh
#
# Serial number and SMBIOS UUID need root. Without it the script still reports
# everything else and matches on MAC address instead.

set -uo pipefail

AGENT_VERSION='1.0.0'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_PATH="${SCRIPT_DIR}/config.json"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        --config)  CONFIG_PATH="${2:-}"; shift 2 ;;
        -h|--help) sed -n '2,25p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

LOG_PATH=''

log() {
    local level="$1"; shift
    local line
    line="$(date '+%Y-%m-%d %H:%M:%S') [${level}] $*"

    echo "$line" >&2

    if [[ -n "$LOG_PATH" ]]; then
        echo "$line" >>"$LOG_PATH" 2>/dev/null || true
    fi
}

die() { log ERROR "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

have_jq() { command -v jq >/dev/null 2>&1; }

# Reads one top-level string from the config. Falls back to a grep when jq is
# absent, which is fine here because the file is ours and flat.
config_value() {
    local key="$1"

    if have_jq; then
        jq -r --arg k "$key" '.[$k] // empty' "$CONFIG_PATH"
    else
        grep -o "\"${key}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$CONFIG_PATH" 2>/dev/null |
            head -1 | sed 's/.*:[[:space:]]*"\(.*\)"/\1/'
    fi
}

config_raw() {
    local key="$1"

    if have_jq; then
        jq -r --arg k "$key" '.[$k] // empty' "$CONFIG_PATH"
    else
        grep -o "\"${key}\"[[:space:]]*:[[:space:]]*[^,}\"]*" "$CONFIG_PATH" 2>/dev/null |
            head -1 | sed 's/.*:[[:space:]]*//' | tr -d ' '
    fi
}

# ---------------------------------------------------------------------------
# JSON escaping
#
# Package names and model strings contain quotes and backslashes often enough
# that building the payload by hand needs this to be right.
# ---------------------------------------------------------------------------

json_escape() {
    local text="$1"

    if have_jq; then
        printf '%s' "$text" | jq -Rs .
        return
    fi

    text="${text//\\/\\\\}"
    text="${text//\"/\\\"}"
    text="${text//$'\t'/\\t}"
    text="${text//$'\r'/}"
    text="${text//$'\n'/\\n}"
    printf '"%s"' "$text"
}

# Emits a JSON key/value pair, or a null when the value is empty, so the server
# sees the same shape whether or not a field could be read.
json_field() {
    local key="$1" value="$2"

    if [[ -z "$value" ]]; then
        printf '"%s":null' "$key"
    else
        printf '"%s":%s' "$key" "$(json_escape "$value")"
    fi
}

json_number() {
    local key="$1" value="$2"

    if [[ -z "$value" || ! "$value" =~ ^[0-9]+$ ]]; then
        printf '"%s":null' "$key"
    else
        printf '"%s":%s' "$key" "$value"
    fi
}

# ---------------------------------------------------------------------------
# Collection
# ---------------------------------------------------------------------------

read_first_line() {
    local path="$1"
    [[ -r "$path" ]] || return 0
    head -1 "$path" 2>/dev/null | tr -d '\0' | sed 's/[[:space:]]*$//'
}

get_machine_uuid() {
    # The SMBIOS UUID survives a reinstall and is what the server prefers for
    # matching. It is root-only; /etc/machine-id is readable by anyone but is
    # regenerated by a reinstall, so it is a fallback rather than an equal.
    local uuid
    uuid="$(read_first_line /sys/class/dmi/id/product_uuid)"

    if [[ -n "$uuid" && ! "$uuid" =~ ^[0-]+$ && ! "$uuid" =~ ^[fF-]+$ ]]; then
        printf '%s' "$uuid"
        return
    fi

    read_first_line /etc/machine-id
}

get_primary_interface() {
    # The interface carrying the default route, not merely the first one up: a
    # server with bonds, bridges, or a VPN has several.
    ip route get 1.1.1.1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "dev") {print $(i+1); exit}}'
}

get_ip_address() {
    local iface="$1"
    [[ -n "$iface" ]] || return 0
    ip -4 addr show "$iface" 2>/dev/null | awk '/inet /{split($2, a, "/"); print a[1]; exit}'
}

get_mac_address() {
    local iface="$1"
    [[ -n "$iface" ]] || return 0
    read_first_line "/sys/class/net/${iface}/address"
}

get_os_name() {
    if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        ( . /etc/os-release && printf '%s' "${NAME:-}" )
    fi
}

get_os_version() {
    if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        ( . /etc/os-release && printf '%s' "${VERSION_ID:-${VERSION:-}}" )
    fi
}

get_cpu_name() {
    awk -F': ' '/^model name/{print $2; exit}' /proc/cpuinfo 2>/dev/null |
        sed 's/^[[:space:]]*//; s/[[:space:]]*$//'
}

get_ram_gb() {
    local kb
    kb="$(awk '/^MemTotal:/{print $2; exit}' /proc/meminfo 2>/dev/null)"
    [[ -n "$kb" ]] || return 0
    # Round to nearest rather than truncating: 7.8 GB of usable memory on an
    # 8 GB machine should not be reported as 7.
    awk -v kb="$kb" 'BEGIN{printf "%d", (kb / 1048576) + 0.5}'
}

get_storage_gb() {
    # Whole physical disks, excluding loop and removable devices, so container
    # overlays and mounted USB media do not inflate the figure.
    local bytes
    bytes="$(lsblk -bdno NAME,SIZE,TYPE,RM 2>/dev/null |
        awk '$3 == "disk" && $4 == 0 {sum += $2} END{print sum+0}')"

    if [[ -z "$bytes" || "$bytes" == '0' ]]; then
        # lsblk is missing on very small images; fall back to mounted filesystems.
        bytes="$(df -B1 --output=size --local -x tmpfs -x devtmpfs -x overlay 2>/dev/null |
            tail -n +2 | awk '{sum += $1} END{print sum+0}')"
    fi

    [[ -n "$bytes" && "$bytes" != '0' ]] || return 0
    awk -v b="$bytes" 'BEGIN{printf "%d", (b / 1073741824) + 0.5}'
}

# Prints one {"name":..,"version":..,"publisher":..,"installed_on":null} per line.
collect_software_lines() {
    if command -v dpkg-query >/dev/null 2>&1; then
        dpkg-query -W -f='${Package}\t${Version}\t${Maintainer}\n' 2>/dev/null
        return
    fi

    if command -v rpm >/dev/null 2>&1; then
        rpm -qa --qf '%{NAME}\t%{VERSION}-%{RELEASE}\t%{VENDOR}\n' 2>/dev/null
        return
    fi

    if command -v pacman >/dev/null 2>&1; then
        pacman -Q 2>/dev/null | awk '{print $1 "\t" $2 "\t"}'
        return
    fi

    if command -v apk >/dev/null 2>&1; then
        apk info -v 2>/dev/null | awk '{print $1 "\t\t"}'
    fi
}

build_software_json() {
    local first=1 line name version publisher

    printf '['

    while IFS=$'\t' read -r name version publisher; do
        [[ -n "${name:-}" ]] || continue

        if [[ $first -eq 0 ]]; then printf ','; fi
        first=0

        printf '{'
        json_field name "$name"; printf ','
        json_field version "${version:-}"; printf ','
        json_field publisher "${publisher:-}"; printf ','
        printf '"installed_on":null'
        printf '}'
    done < <(collect_software_lines | sort -u)

    printf ']'
}

# ---------------------------------------------------------------------------
# Payload
# ---------------------------------------------------------------------------

build_payload() {
    local collect_software="$1"
    local started_at collection_seconds iface software software_count

    started_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    local start_epoch=$SECONDS

    log INFO 'collecting inventory'

    iface="$(get_primary_interface)"

    if [[ "$collect_software" == 'true' ]]; then
        software="$(build_software_json)"
        software_count="$(collect_software_lines | grep -c . || true)"
        log INFO "found ${software_count} installed packages"
    else
        software='[]'
        software_count=0
        log INFO 'software collection disabled in config'
    fi

    collection_seconds=$(( SECONDS - start_epoch ))

    {
        printf '{'
        json_field machine_uuid "$(get_machine_uuid)"; printf ','
        json_field hostname "$(hostname)"; printf ','
        json_field ip_address "$(get_ip_address "$iface")"; printf ','
        json_field mac_address "$(get_mac_address "$iface")"; printf ','
        json_field manufacturer "$(read_first_line /sys/class/dmi/id/sys_vendor)"; printf ','
        json_field model "$(read_first_line /sys/class/dmi/id/product_name)"; printf ','
        json_field serial_number "$(read_first_line /sys/class/dmi/id/product_serial)"; printf ','
        json_field os_name "$(get_os_name)"; printf ','
        json_field os_version "$(get_os_version)"; printf ','
        json_field cpu_name "$(get_cpu_name)"; printf ','
        json_number ram_gb "$(get_ram_gb)"; printf ','
        json_number storage_gb "$(get_storage_gb)"; printf ','
        printf '"installed_software":%s,' "$software"

        # raw_payload is stored verbatim in computer_snapshots, so it carries
        # only this declared set — how the report was produced, not a dump of
        # whatever the machine happened to expose. Putting user accounts, keys,
        # or mounted shares here would place them in the database permanently.
        printf '"raw_payload":{'
        printf '"agent_version":"%s",' "$AGENT_VERSION"
        printf '"agent_platform":"linux",'
        json_field kernel "$(uname -r)"; printf ','
        printf '"collected_at":"%s",' "$started_at"
        printf '"collection_seconds":%s,' "$collection_seconds"
        printf '"software_count":%s' "${software_count:-0}"
        printf '}'
        printf '}'
    }
}

# ---------------------------------------------------------------------------
# Send
# ---------------------------------------------------------------------------

send_payload() {
    local payload="$1" endpoint="$2" token="$3" timeout="$4" max_attempts="$5"
    local attempt response status body retry_after wait

    for (( attempt = 1; attempt <= max_attempts; attempt++ )); do
        response="$(printf '%s' "$payload" | curl -sS -X POST "$endpoint" \
            -H "Authorization: Bearer ${token}" \
            -H 'Content-Type: application/json; charset=utf-8' \
            -H 'Accept: application/json' \
            --max-time "$timeout" \
            --data-binary @- \
            -D - -o - -w '\n__STATUS__%{http_code}' 2>&1)" || true

        status="$(printf '%s' "$response" | sed -n 's/.*__STATUS__\([0-9]*\)$/\1/p')"
        body="$(printf '%s' "$response" | sed 's/__STATUS__[0-9]*$//')"

        if [[ "$status" == '200' ]]; then
            log INFO "accepted: $(printf '%s' "$body" | tr -d '\r' | tail -1)"
            return 0
        fi

        # A rejected token or a malformed payload will be rejected again no
        # matter how many times it is sent.
        if [[ "$status" == '401' ]]; then
            log ERROR 'rejected: the token is not accepted. Check config.json, or regenerate the token in the back-office.'
            return 1
        fi

        if [[ "$status" == '422' ]]; then
            log ERROR "rejected: the server refused the payload as invalid. $(printf '%s' "$body" | tail -1)"
            return 1
        fi

        if (( attempt >= max_attempts )); then
            log ERROR "giving up after ${max_attempts} attempts (status=${status:-none})"
            return 1
        fi

        # The server sends Retry-After when it throttles; honouring it is what
        # keeps a fleet from retrying itself into a longer lockout.
        retry_after="$(printf '%s' "$response" | grep -i '^retry-after:' | head -1 |
            tr -d '\r' | awk '{print $2}')"

        if [[ "$status" == '429' && -n "$retry_after" ]]; then
            wait="$retry_after"
            log WARN "throttled; the server asked for ${wait} seconds"
        else
            wait=$(( 5 * (2 ** attempt) ))
            log WARN "attempt ${attempt} failed (status=${status:-none}); retrying in ${wait} seconds"
        fi

        sleep "$wait"
    done

    return 1
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

[[ -r "$CONFIG_PATH" ]] ||
    die "config not found at ${CONFIG_PATH}. Copy config.example.json to config.json and fill in the endpoint and token."

command -v curl >/dev/null 2>&1 || die 'curl is required but not installed.'

LOG_PATH="$(config_value log_path)"
if [[ -n "$LOG_PATH" ]]; then
    mkdir -p "$(dirname "$LOG_PATH")" 2>/dev/null || true
fi

ENDPOINT="$(config_value endpoint)"
TOKEN="$(config_value token)"

[[ -n "$ENDPOINT" && -n "$TOKEN" ]] || die 'config.json must set both endpoint and token.'

case "$TOKEN" in
    *REPLACE-WITH-THE-TOKEN*)
        die 'config.json still holds the placeholder token from config.example.json.'
        ;;
esac

TIMEOUT="$(config_raw timeout_seconds)"; TIMEOUT="${TIMEOUT:-30}"
MAX_ATTEMPTS="$(config_raw max_attempts)"; MAX_ATTEMPTS="${MAX_ATTEMPTS:-3}"
COLLECT_SOFTWARE="$(config_raw collect_software)"; COLLECT_SOFTWARE="${COLLECT_SOFTWARE:-true}"

PAYLOAD="$(build_payload "$COLLECT_SOFTWARE")"

if [[ $DRY_RUN -eq 1 ]]; then
    log INFO 'dry run: printing the payload instead of sending it'

    if have_jq; then
        printf '%s' "$PAYLOAD" | jq .
    else
        printf '%s\n' "$PAYLOAD"
    fi

    exit 0
fi

send_payload "$PAYLOAD" "$ENDPOINT" "$TOKEN" "$TIMEOUT" "$MAX_ATTEMPTS"
