<x-site.shell :title="$document->title.' — '.hospital_name()"
              :description="Str::limit($document->description, 160)">
    <div class="mx-auto max-w-4xl px-5 py-10 sm:px-6">
        <nav class="mb-5 text-sm text-slate-500">
            <a href="{{ route('site.documents') }}" class="hover:text-brand-600 hover:underline">เอกสารเผยแพร่</a>
            <span class="mx-1.5">/</span>
            <a href="{{ route('site.documents', ['category' => $document->category]) }}" class="hover:text-brand-600 hover:underline">
                {{ $document->category_label }}
            </a>
        </nav>

        <article class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-9">
            <div class="flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between">
                <div class="min-w-0 flex-1">
                    <span class="inline-block rounded-lg bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">
                        {{ $document->category_label }}
                    </span>

                    <h1 class="mt-3 text-2xl font-bold leading-snug text-slate-900 sm:text-3xl">{{ $document->title }}</h1>

                    <dl class="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600">
                        <div>
                            <dt class="text-xs text-slate-500">เผยแพร่</dt>
                            <dd>{{ $document->published_at?->format('d/m/') }}{{ $document->published_at ? thai_year((int) $document->published_at->year) : '' }}</dd>
                        </div>

                        <div>
                            <dt class="text-xs text-slate-500">ชนิดไฟล์</dt>
                            <dd class="uppercase">{{ $document->file_extension }} &middot; {{ $document->file_size_human }}</dd>
                        </div>

                        <div>
                            <dt class="text-xs text-slate-500">ดาวน์โหลด</dt>
                            <dd>{{ number_format($document->download_count) }} ครั้ง</dd>
                        </div>
                    </dl>

                    @if ($document->description)
                        {{-- Plain text, escaped. --}}
                        <div class="mt-5 whitespace-pre-line text-base leading-relaxed text-slate-700">{{ $document->description }}</div>
                    @endif

                    <div class="mt-6 flex flex-wrap gap-2.5">
                        @if ($document->isViewableInBrowser())
                            <a href="{{ route('site.document.preview', $document) }}"
                               target="_blank" rel="noopener"
                               class="inline-flex items-center gap-2 rounded-xl bg-brand-500 px-5 py-2.5 font-semibold text-white hover:bg-brand-600">
                                <x-icon name="search" class="h-4 w-4" />
                                แสดงไฟล์
                            </a>
                        @endif

                        <a href="{{ route('site.document.download', $document) }}"
                           @class([
                               'inline-flex items-center gap-2 rounded-xl px-5 py-2.5 font-semibold',
                               'bg-brand-500 text-white hover:bg-brand-600' => ! $document->isViewableInBrowser(),
                               'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50' => $document->isViewableInBrowser(),
                           ])>
                            <x-icon name="upload" class="h-4 w-4 rotate-180" />
                            ดาวน์โหลด
                        </a>
                    </div>
                </div>

                {{-- Printed onto a notice so people can reach this page on a phone. --}}
                <figure class="shrink-0 rounded-2xl border border-slate-200 p-4 text-center">
                    {{--
                        Unescaped deliberately, and the only place on this site
                        that is. The SVG is generated by BaconQrCode from a URL
                        this application built; no user-entered text reaches it.
                    --}}
                    <div class="mx-auto w-[220px]">{!! $qrCode !!}</div>

                    <figcaption class="mt-2 text-xs text-slate-500">
                        สแกนเพื่อเปิดหน้านี้
                    </figcaption>
                </figure>
            </div>
        </article>

        @if ($document->isViewableInBrowser())
            {{--
                Shown right here so a visitor can read a notice without saving
                it first. The iframe points at the preview route, which serves
                the file under a sandbox policy rather than from the raw
                storage path.
            --}}
            <section class="mt-6">
                <h2 class="mb-3 text-lg font-bold text-slate-900">แสดงไฟล์</h2>

                <div class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200">
                    <iframe src="{{ route('site.document.preview', $document) }}"
                            title="{{ $document->title }}"
                            class="h-[75vh] min-h-[420px] w-full"
                            loading="lazy"></iframe>
                </div>

                <p class="mt-2 text-center text-xs text-slate-500">
                    หากไฟล์ไม่แสดง
                    <a href="{{ route('site.document.preview', $document) }}" target="_blank" rel="noopener"
                       class="font-semibold text-brand-600 hover:underline">เปิดในแท็บใหม่</a>
                    หรือ
                    <a href="{{ route('site.document.download', $document) }}"
                       class="font-semibold text-brand-600 hover:underline">ดาวน์โหลด</a>
                </p>
            </section>
        @endif
    </div>
</x-site.shell>
